services:
  nginx:
    image: nginx
    build:
      context: ./requirements/nginx
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    container_name: nginx
    init : true
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - wordpress
    restart: always
    networks:
      - 42-inception-network
    env_file:
      - ./.env

  wordpress:
    image: wordpress
    build: ./requirements/wordpress
    container_name: wordpress
    init : true
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - mariadb
    restart: always
    networks:
      - 42-inception-network
    env_file:
      - ./.env

  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    container_name: mariadb
    init : true
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - 42-inception-network
    env_file:
      - ./.env

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /home/kishizu/data/wordpress
      o: bind
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/kishizu/data/mariadb
      o: bind

networks:
  42-inception-network:
