CREATE DATABASE wordpress;
CREATE USER "$WORDPRESS_DB_USER"@'%' IDENTIFIED BY "$WORDPRESS_DB_PASSWORD";
GRANT ALL PRIVILEGES ON *.* TO "$WORDPRESS_DB_USER"@'%' WITH GRANT OPTION;
CREATE USER "$WORDPRESS_DB_USER2"@'%' IDENTIFIED BY "$WORDPRESS_DB_PASSWORD2";
GRANT SELECT, LOCK TABLES, SHOW VIEW ON *.* TO "$WORDPRESS_DB_USER2"@'%';
FLUSH PRIVILEGES;